### ISSUE TITLE
What constitutes a valid statblock?

### ISSUE THREAD

**Issue by megazver** [arnonram/swade-npc-importer#114] opened 2022-06-04 13:38 UTC
I've been trying to copy-paste stablocks from the main rulebook (for testing; I already own the SWADE module) and Deadlands core both raw and cleaned up, as well as statblocks from savaged.us and the only response I get is "Failed to parse. Not a valid statblock.

FVTT 9.269, SWADE NPC Importer 0.1.15. 

I'm trying to copy-paste them into the text window, since I am running a client on my PC, but I've also tried it in multiple browsers with same results.

**Comment by arnonram** [comment] 2022-06-04 14:18
Strange, should have no problem with either core or Deadlands...the importer is set to work with pinnacles guidelines to writing stat blocks, and is tested on them regularly

Can you open developer mode (F12 on most browsers) , go to the console tab, and then try to import? Let me know if you see an error there...

What browser are you running on?

**Comment by megazver** [comment] 2022-06-04 14:50
I am self-hosting, so I use the app version, but I've tried logging on through fully updated Chrome, Edge and Firefox. Same error everywhere. 

Tried shutting down every module except NPC importer and the official SWADE module. Same error.

I _think_ I've set the Compendiums correctly.

Here's the relevant section of the console log:

```
SWADE NPC Importer | Starting statblock parsing global.js:28 
SWADE NPC Importer | Failed to prase: TypeError: Cannot read properties of undefined (reading 'replace')
global.js:28 
SWADE NPC Importer | Failed to build finalActor: TypeError: Cannot read properties of undefined (reading 'Name')
global.js:28 
SWADE NPC Importer | Setting parsing language to: en
```

Been using this statblock for testing:

```
Agent
Employed by the shadowy Agency, US Agents investigate espionage and supernatural incidents.

Attributes: Agility d8, Smarts d8, Spirit d6, Strength d6, Vigor d6
Skills: Academics d6, Athletics d6, Common Knowledge d6, Fighting d6, Notice d8, Occult d6, Persuasion d6, Research d6, Shooting d8, Stealth d8, Survival d4
Pace: 6; Parry: 5; Toughness: 5
Edges: Agent, Guts, Level Headed, Rock and Roll!
Hindrances: Cautious, Vow (Major-Destroy or contain the supernatural)
Gear: Gatling pistol (Range 12/24/48, Damage 2d6, RoF 3, AP 1), disguise kit, Agency badge.
```

**Comment by arnonram** [comment] 2022-06-11 08:11
@megazver 
hi, sorry for the delay, been a bit busy

This is a strange case since as i said above, i regularly test on both Deadlands and Core, so the fact that it's not working is strange. I'm also testing on a self-hosted Foundry instance (with both chromium and Firefox).

Some questions:
- When you said you shut down all modules, did you include the Core / Deadlands compendiums? (i do not have the Deadlands compendiums so maybe something there is clashing...)
- Can you open a fresh World and try the importer there?

Thanks :)

**Comment by arnonram** [comment] 2022-10-29 22:18
- cannot reproduce, and no reponse
- i also added some more description to the readme file on stat-blocks

closing issue

**Closed by arnonram** 2022-10-29 22:18 UTC
Labels: question
